services:
  runner:
    image: gh-actions-runner:base
    runtime: sysbox-runc
    restart: always
    environment:
      - ORG=ULE-Informatica-2024-2025
      - TOKEN=<GITHUB_TOKEN_HERE>
      - GROUP=AW
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 2G