services:
  runner:
    image: agutf/actions-runner-prg:latest
    restart: always
    environment:
      - ORG=
      - TOKEN=
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 2G